/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.podcast.kotlin.database.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

import java.io.Serializable;


/**
 * Definition of ObjectType PodCasts.
 *
 * @since 2021-01-06
 */

public class PodCasts extends CloudDBZoneObject implements Serializable {
    @PrimaryKey
    private Integer id;

    private String title;

    private String url;

    private String description;

    private String author;

    private String category;

    private String date;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean isInFavourites;

    public PodCasts() {
        super();
        this.isInFavourites = false;

    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getUrl() {
        return url;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getAuthor() {
        return author;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategory() {
        return category;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }

    public void setIsInFavourites(Boolean isInFavourites) {
        this.isInFavourites = isInFavourites;
    }

    public Boolean getIsInFavourites() {
        return isInFavourites;
    }

}
